#!/usr/bin/env python3
"""
Meta-Skill Process Architect — CLI Tool

Generate standardized process Skills from raw process materials.
Cross-platform: WorkBuddy, OpenClaw, Claude Code, standalone.

Usage:
    python meta-skill-process-architect.py init --name "Process Name" --materials ./path/
    python meta-skill-process-architect.py generate --output ./output/
    python meta-skill-process-architect.py validate --skill ./output/
    python meta-skill-process-architect.py package --format workbuddy --skill ./output/
"""

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path
from datetime import datetime


def slugify(text):
    """Convert text to kebab-case slug."""
    text = text.lower().strip()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_]+', '-', text)
    return text


# ──────────────────────────────────────────────
# Command: init
# ──────────────────────────────────────────────

def cmd_init(args):
    """Initialize a new process analysis session."""
    name = args.name
    materials_path = Path(args.materials).resolve() if args.materials else None
    output_path = Path(args.output or f"process-{slugify(name)}").resolve()

    if output_path.exists():
        print(f"\u26a0\ufe0f  Output directory '{output_path}' already exists.")
        if not args.force:
            print("   Use --force to overwrite.")
            return

    print(f"\U0001f50d Initializing analysis for: {name}")
    if materials_path:
        print(f"\U0001f4c1 Materials: {materials_path}")
    print(f"\U0001f4e6 Output: {output_path}")

    # Create output structure
    dirs = [
        output_path,
        output_path / "references",
        output_path / "agents",
        output_path / "assets",
        output_path / "assets" / "flowcharts",
        output_path / "assets" / "forms",
        output_path / "assets" / "templates",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)

    # Write manifest
    manifest = {
        "process_name": name,
        "created_at": datetime.now().isoformat(),
        "materials_path": str(materials_path) if materials_path else None,
        "status": "initialized",
    }
    with open(output_path / "manifest.json", "w") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    print(f"\u2705 Initialized: {output_path}")
    print(f"   Next: add materials to {materials_path or output_path} and run 'generate'")


# ──────────────────────────────────────────────
# Command: generate
# ──────────────────────────────────────────────

def cmd_generate(args):
    """Generate process Skill from materials."""
    output_path = Path(args.output).resolve()

    if not output_path.exists():
        print(f"\u274c Output directory '{output_path}' does not exist. Run 'init' first.")
        return

    manifest_path = output_path / "manifest.json"
    if manifest_path.exists():
        with open(manifest_path) as f:
            manifest = json.load(f)
    else:
        manifest = {"process_name": output_path.name}

    print(f"\U0001f527 Generating process Skill...")
    print(f"   Output: {output_path}")

    # Phase 1: Generate placeholder files with template structure
    # In production, this would be driven by the agent workflow (SKILL.md)
    # The CLI provides scaffolding; content generation is agent-driven.

    files_created = []

    # Write SKILL.md placeholder if not exists
    skill_md = output_path / "SKILL.md"
    if not skill_md.exists():
        skill_md.write_text(f"---\n"
                           f"name: {manifest.get('process_name', 'process')}\n"
                           f"generated_by_meta_skill_version: {VERSION}\n"
                           f"---\n\n"
                           f"# {manifest.get('process_name', 'Process')}\n\n"
                           f"> Generated by meta-skill-process-architect v{VERSION}\n"
                           f"> Date: {datetime.now().strftime('%Y-%m-%d')}\n\n"
                           f"## Overview\n\n_TODO: Run agent-driven workflow to fill content._\n\n"
                           f"See `references/process-brief.md` for full process definition.\n")
        files_created.append("SKILL.md")

    # Write VERSION (with temporal validity fields)
    version_file = output_path / "VERSION"
    if not version_file.exists():
        version_file.write_text("1.0.0\n"
                               "valid_from: \n"
                               "valid_until: \n"
                               "lifecycle_phase: draft\n"
                               "trial_until: \n")
        files_created.append("VERSION")

    # Write placeholder reference files
    ref_dir = output_path / "references"
    ref_files = {
        "process-brief.md": "# Process Brief\n\n_TODO: Fill L1.1-L1.9 sub-sections._\n",
        "foundational-logic.md": "# Foundational Logic\n\n_TODO: Fill L2 sub-sections._\n",
        "output-recipes.md": "# Output Recipes\n\n_TODO: Fill L3 recipes._\n",
        "artifacts-registry.md": "# Artifacts Registry\n\n_TODO: Fill L4 artifacts._\n",
        "visualization-spec.md": "# Visualization Spec\n\n_TODO: Fill L5 visualization conventions._\n",
        "cases-library.md": "# Cases & Learning Library\n\n_TODO: Fill L6 cases._\n",
    }
    for fname, content in ref_files.items():
        fpath = ref_dir / fname
        if not fpath.exists():
            fpath.write_text(content)
            files_created.append(f"references/{fname}")

    # Update manifest
    manifest["status"] = "generated"
    manifest["generated_at"] = datetime.now().isoformat()
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    if files_created:
        print(f"\u2705 Generated {len(files_created)} files:")
        for f in files_created:
            print(f"   - {f}")
    else:
        print("\u2139\ufe0f  All files already exist. Use --force to regenerate.")

    print(f"   Next: run 'validate' to check quality, then 'package' to bundle.")


# ──────────────────────────────────────────────
# Anti-Pattern Detection
# ──────────────────────────────────────────────

ANTI_PATTERNS = [
    {
        "id": "AP-001",
        "name": "Single-char/short-name role",
        "severity": "warn_confirm",
        "check": lambda skill: _ap001_check(skill),
    },
    {
        "id": "AP-002",
        "name": "Person-name hardcoded as role",
        "severity": "warn_confirm",
        "check": lambda skill: _ap002_check(skill),
    },
    {
        "id": "AP-003",
        "name": "No process owner",
        "severity": "block",
        "check": lambda skill: _ap003_check(skill),
    },
    {
        "id": "AP-004",
        "name": "Zombie/dead-end state",
        "severity": "warn_passive",
        "check": lambda skill: _ap004_check(skill),
    },
    {
        "id": "AP-005",
        "name": "Unclosed branch",
        "severity": "warn_passive",
        "check": lambda skill: _ap005_check(skill),
    },
    {
        "id": "AP-006",
        "name": "No exception path for critical step",
        "severity": "warn_passive",
        "check": lambda skill: _ap006_check(skill),
    },
    {
        "id": "AP-007",
        "name": "Undocumented decisions >= 50%",
        "severity": "warn_confirm",
        "check": lambda skill: _ap007_check(skill),
    },
    {
        "id": "AP-008",
        "name": "No-information trigger",
        "severity": "block",
        "check": lambda skill: _ap008_check(skill),
    },
    {
        "id": "AP-009",
        "name": "Cross-process ref without handoff",
        "severity": "warn_passive",
        "check": lambda skill: _ap009_check(skill),
    },
    {
        "id": "AP-010",
        "name": "All metrics inferred",
        "severity": "warn_passive",
        "check": lambda skill: _ap010_check(skill),
    },
]

NO_INFO_TRIGGERS = ["开始", "start", "启动", "n/a", "none", "无", ""]

# Allowlist: Chinese business/domain terms that should NOT be flagged as role names
# NOTE: Add your industry-specific terms here. The default list uses generic business terms.
CN_BUSINESS_TERMS_ALLOWLIST = [
    # Universal business terms (applicable across industries)
    "工单", "订单", "支付", "退款", "审批", "审核", "入库", "发货",
    "合同", "发票", "报销", "采购", "库存", "物流", "签收",
    # Process-specific non-role terms (add your own)
    "挽单", "蜜月期", "蜜月", "升级", "上报", "归档", "关闭", "退课",
    # Process timing/status terms
    "延期", "解锁", "宽限期", "试运行", "缓冲期",
    # Common workflow nouns
    "申请", "确认", "通知", "记录", "检查", "验证", "分配",
]
# TIP: For industry-specific allowlist entries, extend this list.
# Example for education: add "课程", "班级", "学籍", "升学"
# Example for logistics: add "运单", "仓储", "配送"

# Allowlist: legitimate usage contexts for "快速"/"尽快" that are NOT vague instructions
VAGUE_TERM_WHITELIST = [
    # Section headers / standard UI terms
    "快速上手", "快速查询", "快速索引",
    # Legitimate business descriptions
    "快速学习", "尽快回归", "快速退款", "快速审批", "快速响应",
]


def _read_skill_files(skill_path):
    """Read all text content from a skill directory."""
    content = {}
    skill_dir = Path(skill_path)
    for md_file in skill_dir.rglob("*.md"):
        try:
            content[str(md_file.relative_to(skill_dir))] = md_file.read_text()
        except Exception:
            pass
    # Also read SKILL.md if not .md
    for txt_file in skill_dir.glob("SKILL*"):
        if txt_file.suffix != ".md":
            try:
                content[str(txt_file.relative_to(skill_dir))] = txt_file.read_text()
            except Exception:
                pass
    return content


def _ap001_check(skill):
    """Check for single-char or very short role names."""
    issues = []
    for fname, content in skill.items():
        matches = re.findall(r'(?:role|角色)[：:]\s*["\']?(\S{1,2})["\']?', content, re.IGNORECASE)
        for m in matches:
            if len(m) <= 2 and m not in ["CS", "QA", "PM", "IT", "HR"] and m not in CN_BUSINESS_TERMS_ALLOWLIST:
                issues.append(f"{fname}: role name '{m}' may be too short (AP-001)")
    return issues


def _ap002_check(skill):
    """Check for person names as role names."""
    issues = []
    KNOWN_ROLE_WORDS = ["操作员", "负责人", "审计员", "管理员", "专员", "经理", "主管", "总监",
                        "工程师", "分析师", "代表", "会计", "审核员", "客服", "组长"]
    for fname, content in skill.items():
        matches = re.findall(r'(?:role|角色)[：:]\s*["\']?([\u4e00-\u9fff]{2,3})["\']?', content, re.IGNORECASE)
        for m in matches:
            if m not in KNOWN_ROLE_WORDS and m not in CN_BUSINESS_TERMS_ALLOWLIST:
                issues.append(f"{fname}: '{m}' looks like a person name, not a role (AP-002)")
    return issues


def _ap003_check(skill):
    """Check for missing process owner."""
    issues = []
    all_text = " ".join(skill.values())
    if not re.search(r'(?:process_owner|流程负责人|Process Owner)', all_text, re.IGNORECASE):
        # Check if this is just a placeholder/template (not yet filled)
        if "TODO" not in all_text:
            issues.append("No process owner found in any file (AP-003)")
    return issues


def _ap004_check(skill):
    """Check for zombie states — states with zero inbound or zero outbound transitions (non-terminal).
    
    Phase 1: Stub. Requires full state machine YAML parsing to detect.
    Phase 2: Parse L1.6 YAML blocks, check each state for connectivity.
    Agent workflow (SKILL.md Step 5) handles this check manually in Phase 1.
    """
    return []


def _ap005_check(skill):
    """Check for unclosed branches — step.next has conditions but no default/else branch.
    
    Phase 1: Stub. Requires full step graph with next/condition parsing.
    Phase 2: Parse L1.4 YAML blocks, verify every step with conditional next has a default.
    Agent workflow handles this check manually in Phase 1.
    """
    return []


def _ap006_check(skill):
    """Check for critical steps without exception paths — steps with invariants but no .E/.A sibling.
    
    Phase 3: Full implementation. Parses L1.4 step IDs, identifies critical steps by keywords,
    checks for corresponding .E/.A exception paths.
    """
    issues = []
    brief_content = skill.get("references/process-brief.md", "")
    if not brief_content:
        return issues

    # Extract all step IDs from L1.4
    step_ids = set()
    for match in re.finditer(r'(?:###|####)\s+(S\d+(?:\.\d+)?(?:\.E|\.A)?)', brief_content):
        step_ids.add(match.group(1))

    # Critical keywords: steps that likely need exception paths
    CRITICAL_KEYWORDS = [
        "审批", "退款", "支付", "扣款", "修改", "删除", "变更",
        "approve", "refund", "payment", "delete", "modify",
        "学籍", "订单", "发货", "入库",
    ]
    # Non-critical step markers: simple notifications don't need exception paths
    NON_CRITICAL_MARKERS = ["通知", "确认", "记录", "归档", "notify", "confirm", "log"]

    # Find main step IDs (S1, S2, etc. without .E/.A/.N suffixes)
    main_steps = [sid for sid in step_ids if re.match(r'^S\d+$', sid)]

    for step_id in sorted(main_steps):
        # Check if this step has an exception path
        has_exception = f"{step_id}.E" in step_ids or f"{step_id}.A" in step_ids
        
        if not has_exception:
            # Find the step's content to determine if it's critical
            step_section_pattern = rf'(?:###|####)\s+{re.escape(step_id)}\s*[-—]\s*(.+?)(?=\n(?:###|####|\Z))'
            step_match = re.search(step_section_pattern, brief_content, re.DOTALL)
            if step_match:
                step_body = step_match.group(1)
                is_critical = any(kw in step_body for kw in CRITICAL_KEYWORDS)
                is_non_critical = any(kw in step_body for kw in NON_CRITICAL_MARKERS)
                
                if is_critical and not is_non_critical:
                    issues.append(
                        f"references/process-brief.md: {step_id} has critical keywords but no .E/.A exception path"
                    )
    
    return issues
def _ap007_check(skill):
    """Check for undocumented decisions >= 50%."""
    all_text = " ".join(skill.values())
    total = len(re.findall(r'condition_quality', all_text, re.IGNORECASE))
    undocumented = len(re.findall(r'condition_quality[:\s]*undocumented', all_text, re.IGNORECASE))
    if total > 0 and undocumented / total >= 0.5:
        return [f"{undocumented}/{total} decisions are undocumented (AP-007)"]
    return []


def _ap008_check(skill):
    """Check for no-information trigger."""
    issues = []
    for fname, content in skill.items():
        # Look for trigger.source patterns
        match = re.search(r'(?:trigger.*?source|触发.*?来源)[：:\s]*["\']?(.+?)["\']?(?:\n|$)', content, re.IGNORECASE | re.DOTALL)
        if match:
            trigger_val = match.group(1).strip().lower()
            for bad in NO_INFO_TRIGGERS:
                if trigger_val == bad:
                    issues.append(f"{fname}: trigger is no-information '{trigger_val}' (AP-008)")
                    break
    return issues


def _ap009_check(skill):
    """Check for cross-process references without handoff events.
    
    Phase 1: Stub. Requires full L1.9 scope boundary YAML parsing.
    Phase 2: Parse out_of_scope entries, check handoff_event presence for process-type refs.
    Agent workflow handles this check manually in Phase 1.
    """


def _ap010_check(skill):
    """Check if all metrics are inferred."""
    all_text = " ".join(skill.values())
    total = len(re.findall(r'metric.*?source', all_text, re.IGNORECASE))
    inferred = len(re.findall(r'source[:\s]*inferred', all_text, re.IGNORECASE))
    if total > 0 and inferred == total:
        return ["All metrics have inferred source — recommend Interview Mode (AP-010)"]
    return []


# ──────────────────────────────────────────────
# Command: validate
# ──────────────────────────────────────────────

def cmd_validate(args):
    """Validate a generated process Skill."""
    skill_path = Path(args.skill).resolve()

    if not skill_path.exists():
        print(f"\u274c Skill path '{skill_path}' does not exist.")
        return

    print(f"\U0001f50d Validating: {skill_path}\n")

    content = _read_skill_files(skill_path)
    issues = {"block": [], "warn_confirm": [], "warn_passive": []}
    checks_passed = 0
    checks_total = 0

    # Structural completeness
    print("=" * 60)
    print("Structural Completeness")
    print("=" * 60)
    required_files = [
        "SKILL.md",
        "references/process-brief.md",
        "references/foundational-logic.md",
        "references/output-recipes.md",
    ]
    for f in required_files:
        checks_total += 1
        if f in content:
            print(f"  \u2705 {f} — present")
            checks_passed += 1
        else:
            print(f"  \u274c {f} — MISSING")
            issues["block"].append(f"Missing required file: {f}")

    # Version file
    checks_total += 1
    version_file = skill_path / "VERSION"
    if version_file.exists():
        print(f"  \u2705 VERSION — present")
        checks_passed += 1
    else:
        print(f"  \u26a0\ufe0f VERSION — MISSING (not blocking)")
        issues["warn_passive"].append("Missing VERSION file")

    # Content specificity
    print("\n" + "=" * 60)
    print("Content Specificity")
    print("=" * 60)
    vague_words = ["快速", "尽快", "around", "typically", "快速处理", "尽快回复"]
    all_text = " ".join(content.values())
    vague_found = []
    for w in vague_words:
        if w.lower() in all_text.lower():
            # Check if ALL occurrences are in whitelisted contexts
            # If at least one occurrence is NOT whitelisted, flag it
            occurrences = [m.start() for m in re.finditer(re.escape(w), all_text, re.IGNORECASE)]
            non_whitelisted = 0
            for pos in occurrences:
                context = all_text[max(0, pos-2):pos+len(w)+4]  # surrounding context
                is_whitelisted = any(wl in context for wl in VAGUE_TERM_WHITELIST)
                if not is_whitelisted:
                    non_whitelisted += 1
            if non_whitelisted > 0:
                vague_found.append(f"{w}({non_whitelisted}次非标准用法)")
    checks_total += 1
    if vague_found:
        print(f"  \u26a0\ufe0f Vague terms found: {', '.join(vague_found)}")
        issues["warn_passive"].append(f"Vague terms: {vague_found}")
    else:
        print(f"  \u2705 No vague terms — good specificity")
        checks_passed += 1

    # Role coverage (≥ 3)
    checks_total += 1
    # Match role definition patterns:
    #   1. "### 角色名（`role-id`）" — full pattern
    #   2. "- **角色名** (`role-id`)" — simplified bullet pattern  
    #   3. "### 角色名" — heading-only (legacy format)
    cn_role_pattern = r'###\s+[\u4e00-\u9fff()（）\w]+（`[\w-]+`）'
    en_role_pattern = r'###\s+[\w\s]+\(`[\w-]+`\)'
    # Generic business role suffixes — works across all industries (manufacturing, finance, tech, healthcare, education, etc.)
    bullet_role_pattern = r'[-*]\s+\*\*[\u4e00-\u9fff（）()/]{0,20}(?:经理|主管|专员|负责人|总监|工程师|分析师|操作员|代表|会计|审计|客服|审核|管理员)\*\*\s*\(?`?[\w-]+`?\)?'
    role_count_cn = len(re.findall(cn_role_pattern, all_text))
    role_count_en = len(re.findall(en_role_pattern, all_text))
    role_count_bullet = len(re.findall(bullet_role_pattern, all_text))
    # Also count "| 角色名 |" table headers in role definition tables
    table_role_count = len(re.findall(r'\|\s*[\u4e00-\u9fff]{2,6}(?:经理|主管|专员|负责人|总监|工程师|分析师|操作员|代表|会计|审计|客服|审核|管理员)\s*\|', all_text))
    role_count = max(role_count_cn, role_count_en, role_count_bullet, table_role_count)
    if role_count >= 3:
        print(f"  \u2705 Role coverage: {role_count} roles (>= 3)")
        checks_passed += 1
    else:
        print(f"  \u26a0\ufe0f Role coverage: {role_count} roles (< 3 required)")

    # Source attribution
    checks_total += 1
    if re.search(r'(?:source_attribution|方法论来源|Source Attribution)', all_text, re.IGNORECASE):
        print(f"  \u2705 Source attribution — present")
        checks_passed += 1
    else:
        print(f"  \u26a0\ufe0f Source attribution — MISSING")
        issues["warn_confirm"].append("Missing source attribution in L2")

    # Anti-pattern scan
    print("\n" + "=" * 60)
    print("Anti-Pattern Scan (10 checks)")
    print("=" * 60)
    for ap in ANTI_PATTERNS:
        checks_total += 1
        ap_issues = ap["check"](content)
        if ap_issues:
            print(f"  \u274c {ap['id']} [{ap['severity']}] {ap['name']}")
            for issue in ap_issues:
                print(f"      - {issue}")
            issues[ap["severity"]].extend(ap_issues)
        else:
            print(f"  \u2705 {ap['id']} — clean")
            checks_passed += 1

    # Summary
    print("\n" + "=" * 60)
    print("Validation Summary")
    print("=" * 60)
    print(f"  Passed: {checks_passed}/{checks_total}")

    block_count = len(issues["block"])
    warn_c_count = len(issues["warn_confirm"])
    warn_p_count = len(issues["warn_passive"])

    if block_count > 0:
        print(f"\n  \U0001f6ab BLOCK ({block_count}):")
        for i in issues["block"]:
            print(f"    - {i}")
    if warn_c_count > 0:
        print(f"\n  \u26a0\ufe0f WARN-CONFIRM ({warn_c_count}):")
        for i in issues["warn_confirm"]:
            print(f"    - {i}")
    if warn_p_count > 0:
        print(f"\n  \u2139\ufe0f WARN-PASSIVE ({warn_p_count}):")
        for i in issues["warn_passive"]:
            print(f"    - {i}")

    if block_count == 0 and warn_c_count == 0 and warn_p_count == 0:
        print(f"\n  \u2705 All checks passed! Skill is ready for packaging.")

    # Trace Mode (Phase 3)
    if getattr(args, 'trace', False):
        _run_trace_analysis(skill_path, content, args)

    # Coverage check (Phase 3)
    if getattr(args, 'coverage', False):
        _run_coverage_check(skill_path, content)

    if block_count > 0:
        print(f"\n  \u274c Validation FAILED — {block_count} blocking issues must be resolved.")
        sys.exit(1)
    elif warn_c_count > 0:
        print(f"\n  \u26a0\ufe0f Validation WARNING — {warn_c_count} issues require confirmation.")
    else:
        print(f"\n  \u2705 Validation PASSED.")

def _run_coverage_check(skill_path, content):
    """Check recipe coverage across the 7 standard roles."""
    print("\n" + "=" * 60)
    print("Coverage Check — Role Coverage")
    print("=" * 60)

    recipes_content = content.get("references/output-recipes.md", "")
    brief_content = content.get("references/process-brief.md", "")

    # Standard roles
    STANDARD_ROLES = ["operator", "auditor", "owner", "trainee", "customer", "compliance", "manager"]

    # Extract roles from process-brief
    role_pattern = re.compile(
        r'(?:###\s+([\u4e00-\u9fff()（）\w]+)（`([\w-]+)`）)|'
        r'(?:[-*]\s+\*\*([\u4e00-\u9fff]{2,8}(?:班主任|负责人|老师|主管|财务|客服|质检|销售|教务))\*\*\s*\(?`?([\w-]+)`?\)?)'
    )
    found_roles = {}
    for match in role_pattern.finditer(brief_content):
        if match.group(2):
            found_roles[match.group(2)] = match.group(1)
        elif match.group(4):
            found_roles[match.group(4)] = match.group(3)

    # Check recipe coverage per role
    role_coverage = {}
    for role_id, role_name in found_roles.items():
        # Count recipes that mention this role
        mentions = len(re.findall(re.escape(role_name), recipes_content, re.IGNORECASE))
        role_coverage[role_id] = {"name": role_name, "mentions": mentions}

    covered_roles = sum(1 for r in role_coverage.values() if r["mentions"] > 0)
    total_roles = len(role_coverage)

    print(f"  Total roles: {total_roles}")
    print(f"  Covered (mentioned in recipes): {covered_roles}")
    print(f"")

    for role_id, rc in role_coverage.items():
        status = "\u2705" if rc["mentions"] > 0 else "\u26a0\ufe0f"
        print(f"  {status} {role_id} ({rc['name']}): {rc['mentions']} recipe mentions")

    if covered_roles >= 3:
        print(f"\n  \u2705 Coverage: {covered_roles}/{total_roles} roles covered (>= 3)")
    else:
        uncovered = total_roles - covered_roles
        print(f"\n  \u274c Coverage: only {covered_roles}/{total_roles} roles covered — need >= 3")
        if uncovered > 0:
            print(f"    Recommend generating additional recipes for uncovered roles")
            for role_id, rc in role_coverage.items():
                if rc["mentions"] == 0:
                    # Suggest recipes for this role
                    if role_id in ("operator", "auditor"):
                        print(f"    → {role_id}: SOP + Runbook + FAQ")
                    elif role_id == "owner":
                        print(f"    → {role_id}: RACIO + Compliance Memo")


def _run_trace_analysis(skill_path, content, args):
    """Run Trace Mode analysis comparing documented steps vs observed execution."""
    print("\n" + "=" * 60)
    print("Trace Mode — Drift Analysis")
    print("=" * 60)

    brief_content = content.get("references/process-brief.md", "")
    if not brief_content:
        print("  \u274c process-brief.md not found — cannot run trace")
        return

    # Extract documented steps from L1.4
    step_pattern = re.compile(
        r'(?:###|####)\s+(S\d+(?:\.\d+)?(?:\.E|\.A)?)\s*[-—]\s*(.+?)(?=\n(?:###|####|\Z))',
        re.DOTALL
    )
    documented_steps = {}
    for match in step_pattern.finditer(brief_content):
        step_id = match.group(1)
        step_body = match.group(2)
        # Extract duration
        dur_match = re.search(r'(?:时长|duration)[：:\s]*["\']?(\d+)\s*(?:分钟|min|小时|hour|h|天|day)', step_body, re.IGNORECASE)
        duration = dur_match.group(1) + (dur_match.group(2) or "min") if dur_match else "unknown"
        documented_steps[step_id] = {
            "name": step_body.split("\n")[0].strip()[:60],
            "duration": duration,
        }

    print(f"  Documented steps: {len(documented_steps)}")

    # Load trace source if provided
    observed_steps = {}
    trace_source = getattr(args, 'trace_source', None)
    if trace_source:
        import csv as csv_module
        try:
            with open(trace_source, 'r') as f:
                reader = csv_module.DictReader(f)
                for row in reader:
                    # Expect: step_id, duration_minutes, status, note
                    sid = row.get('step_id', row.get('from_status', ''))
                    if sid:
                        observed_steps[sid] = {
                            "duration_min": float(row.get('duration_minutes', 0)),
                            "status": row.get('status', ''),
                            "note": row.get('note', ''),
                        }
            print(f"  Observed steps (from trace source): {len(observed_steps)}")
        except Exception as e:
            print(f"  \u26a0\ufe0f  Could not read trace source: {e}")

    # Load SLA report if provided
    sla_data = {}
    sla_report = getattr(args, 'sla_report', None)
    if sla_report:
        import csv as csv_module
        try:
            with open(sla_report, 'r') as f:
                reader = csv_module.DictReader(f)
                for row in reader:
                    sid = row.get('step_id', '')
                    if sid:
                        sla_data[sid] = {
                            "target_h": float(row.get('sla_target_hours', 0)),
                            "actual_h": float(row.get('actual_median_hours', 0)),
                            "breach_pct": float(row.get('breach_rate_pct', 0)),
                        }
            print(f"  SLA data points: {len(sla_data)}")
        except Exception as e:
            print(f"  \u26a0\ufe0f  Could not read SLA report: {e}")

    # Classification
    print("\n  Step Classification:")
    print(f"  {'Step':<10} {'Status':<12} {'Doc Duration':<15} {'Observed':<15}")
    print(f"  {'-'*10} {'-'*12} {'-'*15} {'-'*15}")

    matched = shadow = dead = drifted = unobserved = 0

    for step_id, doc_info in documented_steps.items():
        if step_id in observed_steps:
            obs = observed_steps[step_id]
            # Simple drift check: compare durations if we have numeric data
            status = "matched"
            dur_match = re.search(r'(\d+)', doc_info["duration"])
            if dur_match:
                doc_min = float(dur_match.group(1))
                obs_min = obs["duration_min"]
                if obs_min > 0:
                    delta_pct = abs(obs_min - doc_min) / doc_min * 100
                    if delta_pct > 30:
                        status = "drifted"

            if status == "matched":
                matched += 1
            else:
                drifted += 1

            print(f"  {step_id:<10} {status:<12} {doc_info['duration']:<15} {obs['duration_min']}min")
        else:
            unobserved += 1
            print(f"  {step_id:<10} unobserved   {doc_info['duration']:<15} (no data)")

    # Check for shadow steps (in observed but not documented)
    for obs_id in observed_steps:
        if obs_id not in documented_steps:
            shadow += 1
            print(f"  {obs_id:<10} shadow       {'(not in doc)':<15} {observed_steps[obs_id]['duration_min']}min")

    # SLA drift
    if sla_data:
        print(f"\n  SLA Drift:")
        for sid, sla in sla_data.items():
            if sla["breach_pct"] > 20:
                print(f"    \u26a0\ufe0f  {sid}: SLA target {sla['target_h']}h, actual {sla['actual_h']}h, breach {sla['breach_pct']}%")

    # Score
    total = len(documented_steps) + shadow
    drift_score = (shadow + dead + drifted) / max(total, 1) * 100

    print(f"\n  Trace Summary:")
    print(f"    Documented steps: {len(documented_steps)}")
    print(f"    Matched: {matched}")
    print(f"    Shadow (undocumented): {shadow}")
    print(f"    Dead (never executed): {dead}")
    print(f"    Drifted (duration/executor): {drifted}")
    print(f"    Unobserved: {unobserved}")
    print(f"    Drift Score: {drift_score:.1f}%")

    if drift_score <= 10:
        print(f"    Status: \u2705 Healthy")
    elif drift_score <= 25:
        print(f"    Status: \u26a0\ufe0f  Warning — schedule review")
    elif drift_score <= 50:
        print(f"    Status: \U0001f534 Unhealthy — escalate to process owner")
    else:
        print(f"    Status: \U0001f6a8 Critical — document unreliable, full re-extraction needed")

    # Output to file if requested
    output_file = getattr(args, 'output', None)
    if output_file:
        import yaml as yaml_module
        try:
            report = {
                "process": str(skill_path.name),
                "analysis_date": datetime.now().isoformat(),
                "summary": {
                    "baseline_steps": len(documented_steps),
                    "matched": matched,
                    "shadow_steps": shadow,
                    "dead_steps": dead,
                    "drifted_steps": drifted,
                    "unobserved": unobserved,
                    "drift_score": round(drift_score, 1),
                    "health": "healthy" if drift_score <= 10 else ("warning" if drift_score <= 25 else ("unhealthy" if drift_score <= 50 else "critical")),
                }
            }
            with open(output_file, 'w') as f:
                yaml_module.dump(report, f, default_flow_style=False, allow_unicode=True)
            print(f"\n  \u2705 Trace report saved: {output_file}")
        except ImportError:
            print(f"\n  \u26a0\ufe0f  PyYAML not installed, skipping report file")


# ──────────────────────────────────────────────
# Command: package
# ──────────────────────────────────────────────

def cmd_package(args):
    """Package a process Skill for distribution."""
    skill_path = Path(args.skill).resolve()
    fmt = args.format  # workbuddy, openclaw, claude-code, standalone

    if not skill_path.exists():
        print(f"\u274c Skill path '{skill_path}' does not exist.")
        return

    print(f"\U0001f4e6 Packaging: {skill_path}")
    print(f"   Format: {fmt}")

    # Exclude patterns that should never be in a distribution package
    EXCLUDE_DIRS = {".git", ".github", ".workbuddy", "__pycache__"}
    EXCLUDE_FILES = {".DS_Store", ".gitignore"}

    def _should_exclude(name):
        """Check if a file/dir should be excluded from packaging."""
        basename = name.split("/")[-1] if "/" in name else name
        return basename in EXCLUDE_DIRS or basename in EXCLUDE_FILES or basename.startswith("._") or basename.endswith(".pyc")

    if fmt == "workbuddy" or fmt == "openclaw":
        # Create tar.gz for WorkBuddy/OpenClaw import
        output_file = skill_path.parent / f"{skill_path.name}.tar.gz"
        import tarfile
        with tarfile.open(output_file, "w:gz") as tar:
            for item in skill_path.rglob("*"):
                # Skip excluded patterns
                parts = item.relative_to(skill_path).parts
                if any(_should_exclude(p) for p in parts):
                    continue
                tar.add(item, arcname=str(item.relative_to(skill_path.parent)))
        print(f"\u2705 Packaged: {output_file}")
        if fmt == "workbuddy":
            print(f"   Import via WorkBuddy: Skills → Import → {output_file.name}")
        else:
            print(f"   Import via OpenClaw: skills install {output_file}")


# ──────────────────────────────────────────────
# Command: bump
# ──────────────────────────────────────────────

BUMP_ORDER = {"PATCH": 2, "MINOR": 1, "MAJOR": 0}


def _parse_version(version_str):
    """Parse 'X.Y.Z' into (int, int, int)."""
    parts = version_str.strip().split(".")
    if len(parts) != 3:
        raise ValueError(f"Invalid version format: {version_str}")
    return int(parts[0]), int(parts[1]), int(parts[2])


def _bump_version(current, bump_type):
    """Bump version according to semver."""
    major, minor, patch = _parse_version(current)
    if bump_type == "MAJOR":
        return f"{major + 1}.0.0"
    elif bump_type == "MINOR":
        return f"{major}.{minor + 1}.0"
    elif bump_type == "PATCH":
        return f"{major}.{minor}.{patch + 1}"
    else:
        raise ValueError(f"Unknown bump type: {bump_type}")


def _get_current_quarter():
    """Return current quarter as YYYY-Q#."""
    now = datetime.now()
    quarter = (now.month - 1) // 3 + 1
    return f"{now.year}-Q{quarter}"


def cmd_bump(args):
    """Bump version and update CHANGELOG for a process Skill."""
    skill_path = Path(args.skill).resolve()
    bump_type = args.type.upper()
    message = args.message

    if bump_type not in ("MAJOR", "MINOR", "PATCH"):
        print(f"\u274c Invalid bump type: {bump_type}. Use MAJOR, MINOR, or PATCH.")
        return

    version_file = skill_path / "VERSION"
    changelog_file = skill_path / "CHANGELOG.md"

    if not version_file.exists():
        print(f"\u274c VERSION file not found in {skill_path}")
        return

    current_version = version_file.read_text().strip()
    new_version = _bump_version(current_version, bump_type)

    print(f"\U0001f4e6 Bump: {current_version} → {new_version} ({bump_type})")
    print(f"   Message: {message}")
    print(f"   Skill: {skill_path}")

    if args.dry_run:
        print(f"\n   [DRY RUN] Would update:")
        print(f"     VERSION: {current_version} → {new_version}")
        print(f"     CHANGELOG.md: append [{new_version}] entry")
        return

    # Update VERSION
    version_file.write_text(new_version + "\n")
    print(f"   \u2705 VERSION updated: {new_version}")

    # Update CHANGELOG
    quarter = _get_current_quarter()
    date_str = datetime.now().strftime("%Y-%m-%d")
    new_entry = f"""## [{new_version}] — {quarter} ({date_str})

### Changed
- {message}

"""
    if changelog_file.exists():
        existing = changelog_file.read_text()
        # Insert after the first line (title) or at the top
        lines = existing.split("\n")
        if lines and lines[0].startswith("# "):
            changelog_file.write_text(lines[0] + "\n\n" + new_entry + "\n".join(lines[1:]).lstrip("\n"))
        else:
            changelog_file.write_text(new_entry + existing)
    else:
        changelog_file.write_text(f"# Changelog — {skill_path.name}\n\n" + new_entry)

    print(f"   \u2705 CHANGELOG updated")

    # Update temporal fields in VERSION if --phase provided
    if hasattr(args, 'phase') and args.phase:
        version_lines = version_file.read_text().strip().split("\n")
        new_lines = []
        valid_from = getattr(args, 'valid_from', None) or date_str
        trial_until = getattr(args, 'trial_until', None) or ""
        for line in version_lines:
            if line.startswith("valid_from:"):
                new_lines.append(f"valid_from: {valid_from}")
            elif line.startswith("valid_until:"):
                new_lines.append("valid_until: ")
            elif line.startswith("lifecycle_phase:"):
                new_lines.append(f"lifecycle_phase: {args.phase}")
            elif line.startswith("trial_until:"):
                new_lines.append(f"trial_until: {trial_until}" if args.phase == "trial" and trial_until else "trial_until: ")
            elif line and not line.startswith("valid_") and not line.startswith("lifecycle_") and not line.startswith("trial_"):
                new_lines.append(line)
        version_file.write_text("\n".join(new_lines) + "\n")
        print(f"   \u2705 VERSION temporal fields updated (phase={args.phase}, valid_from={valid_from})")

    # If previous version was active and this is a new version, mark old version as superseded
    if hasattr(args, 'phase') and args.phase and current_version != new_version:
        # Mark previous version's valid_until
        old_valid_until = valid_from if hasattr(args, 'valid_from') and args.valid_from else date_str
        print(f"   \u2139\ufe0f  Previous version ({current_version}) is now superseded (valid_until={old_valid_until})")

    print(f"\n   Next: run 'validate' to confirm no regressions.")


# ──────────────────────────────────────────────
# Command: which-version
# ──────────────────────────────────────────────

def cmd_which_version(args):
    """Query which process version was active on a given date."""
    from datetime import date as date_type

    skill_path = Path(args.skill).resolve()
    changelog_file = skill_path / "CHANGELOG.md"
    version_file = skill_path / "VERSION"

    if args.list:
        # List all versions with temporal windows
        if not changelog_file.exists():
            print(f"\u26a0\ufe0f  No CHANGELOG found in {skill_path}")
            return

        content = changelog_file.read_text()
        versions = []
        for line in content.split("\n"):
            if line.startswith("## [") and " — " in line:
                ver_part = line.split("## [")[1].split("]")[0]
                rest = line.split("] — ")[1] if "] — " in line else ""
                versions.append(f"  v{ver_part}  {rest}")

        if versions:
            print(f"\U0001f4c5 Versions for {skill_path.name}:")
            for v in versions:
                print(v)
        else:
            print("\u2139\ufe0f  No version entries found in CHANGELOG.")
        return

    if not args.at:
        # If no date specified and no --list, show current version info
        if version_file.exists():
            content = version_file.read_text()
            print(f"\U0001f4c5 {skill_path.name}:")
            print(content)
        else:
            print(f"\u26a0\ufe0f  No VERSION file found in {skill_path}")
        return

    # Parse query date
    try:
        query_date = date_type.fromisoformat(args.at)
    except ValueError:
        print(f"\u274c Invalid date format: {args.at}. Use YYYY-MM-DD.")
        return

    # Scan VERSION file for temporal info
    if version_file.exists():
        v_content = version_file.read_text()
        phase = "unknown"
        for line in v_content.split("\n"):
            if line.startswith("lifecycle_phase:"):
                phase = line.split(":", 1)[1].strip()

        version_num = v_content.split("\n")[0].strip()

        if args.phase:
            print(f"v{version_num}: {phase}")
            if phase == "trial":
                for line in v_content.split("\n"):
                    if line.startswith("trial_until:") and line.split(":", 1)[1].strip():
                        print(f"  trial until: {line.split(':', 1)[1].strip()}")
            return

        # Scan CHANGELOG for temporal windows
        if changelog_file.exists():
            content = changelog_file.read_text()
            best_match = None
            for line in content.split("\n"):
                if line.startswith("## [") and " — " in line:
                    # Parse: ## [X.Y.Z] — YYYY-MM-DD (phase, trial until YYYY-MM-DD)
                    try:
                        ver_part = line.split("## [")[1].split("]")[0]
                        date_part = line.split("] — ")[1].split(" ")[0] if "] — " in line else None
                        if date_part:
                            entry_date = date_type.fromisoformat(date_part)
                            if entry_date <= query_date:
                                if best_match is None or date_type.fromisoformat(best_match[1]) < entry_date:
                                    best_match = (ver_part, date_part, line)
                    except (ValueError, IndexError):
                        continue

            if best_match:
                print(f"\U0001f4c5 At {args.at}, authoritative version: v{best_match[0]}")
                print(f"   (effective from {best_match[1]})")
                print(f"   {best_match[2]}")
                return

    # Fallback: just show current version
    print(f"\U0001f4c5 {skill_path.name}: v{version_num} ({phase})")
    print(f"   (no temporal window info available for date {args.at})")



# ──────────────────────────────────────────────
# Command: ttl-check
# ──────────────────────────────────────────────

def cmd_ttl_check(args):
    """Scan process Skill(s) for TTL expiry."""
    if args.skills:
        skill_dirs = [Path(d).resolve() for d in args.skills.split(",")]
    elif args.skill:
        skill_dirs = [Path(args.skill).resolve()]
    else:
        print("\u274c Specify --skill or --skills")
        return

    current_quarter = _get_current_quarter()
    # Parse "YYYY-Q#" to numeric: YYYY*4 + Q - 1
    year_part = int(current_quarter[:4])
    quarter_part = int(current_quarter[6])  # "YYYY-Q#", Q# is at index 5-6
    current_q_num = year_part * 4 + quarter_part - 1

    def _parse_quarter(q_str):
        """Parse 'YYYY-Q#' to numeric quarter index."""
        parts = q_str.strip().split("-Q")
        if len(parts) != 2:
            return None
        return int(parts[0]) * 4 + int(parts[1]) - 1

    print("=" * 60)
    print(f"TTL Check Report")
    print(f"Current quarter: {current_quarter}")
    print("=" * 60)

    total_valid = 0
    total_expiring = 0
    total_expired = 0
    total_missing = 0
    total_checked = 0

    for skill_dir in skill_dirs:
        if not skill_dir.exists():
            print(f"\n\u26a0\ufe0f  Skill directory not found: {skill_dir}")
            continue

        print(f"\n\U0001f50d {skill_dir.name}")

        # Scan all .md files for @valid_until markers
        ttl_pattern = re.compile(r'@valid_until=(\d{4}-Q[1-4])')
        expired = []
        expiring = []
        valid = []

        for md_file in sorted(skill_dir.rglob("*.md")):
            try:
                content = md_file.read_text()
                for match in ttl_pattern.finditer(content):
                    q_str = match.group(1)
                    line_num = content[:match.start()].count("\n") + 1
                    # Extract surrounding context (the field name)
                    line_start = content.rfind("\n", 0, match.start()) + 1
                    line_end = content.find("\n", match.end())
                    context = content[line_start:line_end].strip()[:80]

                    q_num = _parse_quarter(q_str)
                    total_checked += 1

                    if q_num is None:
                        continue
                    elif q_num < current_q_num:
                        expired.append((md_file.relative_to(skill_dir), line_num, q_str, context))
                        total_expired += 1
                    elif q_num == current_q_num:
                        expiring.append((md_file.relative_to(skill_dir), line_num, q_str, context))
                        total_expiring += 1
                    else:
                        valid.append((md_file.relative_to(skill_dir), line_num, q_str, context))
                        total_valid += 1
            except Exception:
                pass

        if expired:
            print(f"  \u274c EXPIRED ({len(expired)}):")
            for fname, line, q, ctx in expired:
                print(f"    {fname}:{line} — {q} — {ctx}")
        if expiring:
            print(f"  \u26a0\ufe0f  EXPIRING ({len(expiring)}):")
            for fname, line, q, ctx in expiring:
                print(f"    {fname}:{line} — {q} — {ctx}")
        if valid and args.verbose:
            print(f"  \u2705 VALID ({len(valid)}):")
            for fname, line, q, ctx in valid:
                print(f"    {fname}:{line} — {q}")
        elif valid:
            print(f"  \u2705 VALID: {len(valid)} markers")
        if not expired and not expiring and not valid:
            print(f"  \u2139\ufe0f  No TTL markers found")

    # Summary
    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"  Total markers checked: {total_checked}")
    print(f"  \u2705 Valid: {total_valid}")
    print(f"  \u26a0\ufe0f  Expiring: {total_expiring}")
    print(f"  \u274c Expired: {total_expired}")

    if total_expired > 0:
        print(f"\n  \u26a0\ufe0f  {total_expired} TTL markers EXPIRED. Run 'diff-plan' to assess impact.")
    elif total_expiring > 0:
        print(f"\n  \u2139\ufe0f  {total_expiring} TTL markers expiring this quarter. Schedule review.")
    else:
        print(f"\n  \u2705 All TTL markers valid.")


# ──────────────────────────────────────────────
# Command: diff-plan
# ──────────────────────────────────────────────

def cmd_diff_plan(args):
    """Compare current Skill with baseline and output impact assessment."""
    skill_path = Path(args.skill).resolve()
    since = args.since

    if not skill_path.exists():
        print(f"\u274c Skill path '{skill_path}' does not exist.")
        return

    print("=" * 60)
    print(f"Diff-Plan: {skill_path.name}")
    print(f"Baseline: {since}")
    print("=" * 60)

    # Load current process-brief.md
    brief_path = skill_path / "references" / "process-brief.md"
    if not brief_path.exists():
        print(f"\n\u274c process-brief.md not found in {skill_path}/references/")
        print(f"   Cannot perform diff without process-brief.md")
        return

    current_brief = brief_path.read_text()

    # If --since is a version number, try to find baseline in same directory
    # For now, baseline comparison is best-effort
    baseline_brief = None
    if since:
        # Try git
        import subprocess
        try:
            result = subprocess.run(
                ["git", "log", "--oneline", "-1"],
                cwd=skill_path, capture_output=True, text=True, timeout=5
            )
            if result.returncode == 0:
                print(f"\n  Git HEAD: {result.stdout.strip()}")
        except Exception:
            pass

    # Extract key fields from current brief
    changes = []

    # Count steps
    steps = re.findall(r'(?:###|####)\s+S\d+', current_brief)
    step_count = len(steps)
    print(f"\n  L1.4 Steps detected: {step_count}")

    # Count roles
    role_matches = re.findall(
        r'[-*]\s+\*\*([\u4e00-\u9fff]{2,8}(?:班主任|负责人|老师|主管|财务|客服|质检|销售|教务))\*\*',
        current_brief
    )
    role_count = len(set(role_matches))
    print(f"  L1.3 Roles detected: {role_count}")

    # Detect SLA values
    sla_matches = re.findall(
        r'(?:SLA|sla)[：:\s]*["\']?(\d+)\s*(?:小时|hour|h|天|day|d|分钟|minute|min|工作日|business day)',
        current_brief, re.IGNORECASE
    )
    if sla_matches:
        print(f"  L1.8 SLA values: {', '.join(sla_matches)}")

    # Detect TTL markers
    ttl_matches = re.findall(r'@valid_until=(\d{4}-Q[1-4])', current_brief)
    if ttl_matches:
        print(f"  TTL markers: {len(ttl_matches)}")

    # Detect handoff events
    handoff_matches = re.findall(r'handoff_event', current_brief, re.IGNORECASE)
    if handoff_matches:
        print(f"  Handoff events: {len(handoff_matches)}")

    # If new materials provided, do deeper comparison
    if args.new_materials:
        mat_path = Path(args.new_materials).resolve()
        if mat_path.exists():
            print(f"\n  Comparing with new materials: {mat_path}")
            new_mats = {}
            for f in mat_path.rglob("*.md"):
                try:
                    new_mats[str(f.relative_to(mat_path))] = f.read_text()
                except Exception:
                    pass
            if new_mats:
                print(f"  New material files: {len(new_mats)}")

    # Output impact assessment
    print("\n" + "-" * 40)
    print("Impact Assessment")
    print("-" * 40)

    if step_count == 0:
        print("  \u26a0\ufe0f  No steps detected — L1.4 may be empty or in non-standard format")

    suggested_bump = "PATCH"
    if args.new_materials:
        suggested_bump = "MINOR"
    elif not baseline_brief:
        print("  \u2139\ufe0f  No baseline available for full diff comparison")
        print(f"  Suggested bump: {suggested_bump} (conservative)")
        print(f"  To compare against a specific version:")
        print(f"    process-architect diff-plan --skill {skill_path} --since 1.0.0")
    else:
        print(f"  Suggested bump: {suggested_bump}")

    print(f"\n  CLI command to apply:")
    print(f"    process-architect bump --skill {skill_path} --type {suggested_bump.lower()} \"Describe changes here\"")


# ──────────────────────────────────────────────
# Command: impact (Phase 5)
# ──────────────────────────────────────────────

def cmd_impact(args):
    """Run impact analysis for a process change."""
    skill_path = Path(args.skill).resolve() if args.skill else None
    skills_dir = Path(args.skills_dir).resolve() if hasattr(args, 'skills_dir') and args.skills_dir else None
    change_type = args.change_type

    print("=" * 60)
    print("Impact Analysis")
    print("=" * 60)

    # Direct impact analysis
    if skill_path and skill_path.exists():
        print(f"\n\U0001f50d Process: {skill_path.name}")
        
        brief_path = skill_path / "references" / "process-brief.md"
        if not brief_path.exists():
            print(f"  \u26a0\ufe0f  No process-brief.md found — skipping direct impact analysis")
        else:
            brief = brief_path.read_text()
            direct_impacts = []
            
            if change_type == "sla":
                step = getattr(args, 'step', None)
                old_val = getattr(args, 'old', None)
                new_val = getattr(args, 'new', None)
                print(f"  Change: SLA {step or 'overall'} — {old_val} → {new_val}")
                
                # Find the step
                if step:
                    step_pattern = re.compile(
                        rf'(?:###|####)\s+{re.escape(step)}\s*[-—].*?(?=\n(?:###|####|\Z))',
                        re.DOTALL
                    )
                    step_match = step_pattern.search(brief)
                    if step_match:
                        direct_impacts.append(f"L1.4 {step}: duration shortened from {old_val} to {new_val}")
                        # Check for exception paths
                        has_e = f"{step}.E" in brief
                        has_a = f"{step}.A" in brief
                        if has_e:
                            direct_impacts.append(f"  → {step}.E exception path SLA may need recalibration")
                        if has_a:
                            direct_impacts.append(f"  → {step}.A alternate path SLA may need recalibration")
                    else:
                        print(f"  \u26a0\ufe0f  Step {step} not found in process-brief")
                
                # Cycle time impact
                dur_matches = re.findall(
                    r'(?:时长|duration)[：:\s]*.*?(\d+)\s*(?:小时|hour|h|天|day)',
                    brief, re.IGNORECASE
                )
                if dur_matches:
                    print(f"  \U0001f4ca Cycle time: {len(dur_matches)} duration values found (recalculate total)")

            elif change_type == "role":
                old_name = getattr(args, 'old_name', None)
                new_name = getattr(args, 'new_name', None)
                print(f"  Change: Role rename — {old_name} → {new_name}")
                
                # Find all occurrences
                mentions = brief.count(old_name) if old_name else 0
                if mentions > 0:
                    direct_impacts.append(f"Role '{old_name}' appears {mentions} times in process-brief.md")
                    direct_impacts.append(f"  → All L1.4 steps referencing this role need executor_role update")
                    direct_impacts.append(f"  → RACI matrix (L1.7) needs role name update")
                    direct_impacts.append(f"  → All generated recipes must be regenerated with new role name")

            elif change_type == "tool":
                old_url = getattr(args, 'old_url', None)
                new_url = getattr(args, 'new_url', None)
                print(f"  Change: Tool URL — {old_url} → {new_url}")
                
                mentions = brief.count(old_url) if old_url else 0
                if mentions > 0:
                    direct_impacts.append(f"Tool URL appears {mentions} times in process-brief.md")
                    direct_impacts.append(f"  → Update L1.4 step descriptions and L1.2 input entries")
                else:
                    print(f"  \u26a0\ufe0f  Old URL not found in process-brief.md — no direct impacts")

            elif change_type == "auto":
                print(f"  Auto-detecting changes from baseline...")
                since = getattr(args, 'since', None)
                if since:
                    direct_impacts.append(f"Comparing current version against baseline: {since}")
                    direct_impacts.append(f"  → Run full diff-plan for detailed change list")
                    # Reuse diff-plan logic
                    steps = re.findall(r'(?:###|####)\s+S\d+', brief)
                    roles = re.findall(
                        r'[-*]\s+\*\*([\u4e00-\u9fff]{2,8}(?:班主任|负责人|老师|主管|财务|客服|质检|销售|教务))\*\*',
                        brief
                    )
                    sla_vals = re.findall(
                        r'(?:SLA|sla)[：:\s]*["\']?(\d+)\s*(?:小时|hour|h|天|day)',
                        brief, re.IGNORECASE
                    )
                    direct_impacts.append(f"  Detected: {len(steps)} steps, {len(set(roles))} roles, {len(sla_vals)} SLA values")

            # Print direct impacts
            if direct_impacts:
                print(f"\n  Direct Impacts ({len(direct_impacts)}):")
                for imp in direct_impacts:
                    print(f"    • {imp}")
            else:
                print(f"\n  ✅ No direct impacts detected on this process")

            # Suggested bump
            bump_map = {"sla": "MINOR", "role": "MINOR", "tool": "PATCH", "step": "MINOR", "step-remove": "MAJOR", "regulatory": "MAJOR", "auto": "PATCH"}
            suggested = bump_map.get(change_type, "PATCH")
            print(f"\n  Suggested bump: {suggested}")
            print(f"    process-architect bump --skill {skill_path} --type {suggested.lower()} \"{change_type} change: {getattr(args, 'old', getattr(args, 'old_name', getattr(args, 'old_url', 'auto-detected')))}\"")

    # Cross-process impact (if skills-dir provided)
    if skills_dir and skills_dir.exists():
        print(f"\n  \U0001f310 Cross-Process Impact:")
        process_dirs = sorted([d for d in skills_dir.iterdir()
                              if d.is_dir() and d.name.startswith("process-") and d.name != (skill_path.name if skill_path else "")])
        
        if not process_dirs:
            print(f"    No other process Skills found in {skills_dir}")
        else:
            downstream = []
            for pd in process_dirs:
                brief_p = pd / "references" / "process-brief.md"
                if not brief_p.exists():
                    continue
                content = brief_p.read_text()
                # Check if this process references our changed process
                skill_name = skill_path.name if skill_path else ""
                if skill_name and (skill_name in content or skill_path.name.replace("process-", "") in content):
                    # Find handoff references
                    handoff_matches = re.findall(
                        r'[-*]\s+\*\*(.+?)\*\*\s*\n.*?指向[：:]\s*(.+?)(?:\n|$)',
                        content, re.DOTALL
                    )
                    for desc, target in handoff_matches:
                        if skill_name in target or skill_path.name.replace("process-", "") in target:
                            downstream.append({
                                "process": pd.name,
                                "handoff_desc": desc,
                                "target": target,
                            })
            
            if downstream:
                print(f"    {len(downstream)} downstream process(es) affected:")
                for ds in downstream:
                    print(f"    \u26a0\ufe0f  {ds['process']} — handoff: {ds['handoff_desc']}")
                    print(f"       → Review {ds['process']}/references/process-brief.md L1.9")
                
                # SLA cascade check
                print(f"\n    SLA Cascade Check:")
                print(f"      ⚠️  Manual review required — verify downstream SLA deadlines are still achievable")
                if change_type == "sla":
                    print(f"      → If upstream changed, downstream handoff SLA margin may shrink")
            else:
                print(f"    ✅ No downstream processes reference this process")

    # Risk classification
    print(f"\n  Risk Classification:")
    if change_type in ("regulatory", "step-remove"):
        print(f"    \U0001f534 HIGH — {change_type} changes require careful review")
    elif change_type in ("role", "step"):
        print(f"    \U0001f7e1 MEDIUM — Review affected processes before proceeding")
    else:
        print(f"    \U0001f7e2 LOW — Isolated change, auto-approve with notification")

    # Output to file
    output_file = getattr(args, 'output', None)
    if output_file:
        import json as json_module
        report = {
            "change_type": change_type,
            "process": str(skill_path) if skill_path else None,
            "direct_impacts": direct_impacts if 'direct_impacts' in dir() else [],
            "suggested_bump": suggested,
            "generated_at": datetime.now().isoformat(),
        }
        with open(output_file, 'w') as f:
            json_module.dump(report, f, indent=2, ensure_ascii=False)
        print(f"\n  \u2705 Impact report saved: {output_file}")


# ──────────────────────────────────────────────
# Command: network (Phase 3)
# ──────────────────────────────────────────────

def cmd_network(args):
    """Build Cross-Process Network from process Skills."""
    if args.skills:
        skills_dir = Path(args.skills).resolve()
    elif args.skill and getattr(args, 'skills_dir', None):
        skills_dir = Path(args.skills_dir).resolve()
    else:
        print("\u274c Specify --skills (directory) or --skill + --skills-dir")
        return

    if not skills_dir.exists():
        print(f"\u274c Directory not found: {skills_dir}")
        return

    print("=" * 60)
    print(f"Cross-Process Network: {skills_dir.name}")
    print("=" * 60)

    # Discover all process-* directories
    process_dirs = sorted([d for d in skills_dir.iterdir()
                          if d.is_dir() and d.name.startswith("process-")])

    if not process_dirs:
        print(f"\n  \u26a0\ufe0f  No process-* directories found in {skills_dir}")
        return

    print(f"\n  Skills found: {len(process_dirs)}")
    for pd in process_dirs:
        print(f"    - {pd.name}")

    # Build network
    nodes = {}
    edges = []
    unresolved_refs = []
    missing_backlinks = []

    # First pass: index all Skills
    for pd in process_dirs:
        brief_path = pd / "references" / "process-brief.md"
        skill_md = pd / "SKILL.md"
        name = pd.name

        # Extract process name from SKILL.md title
        try:
            skill_content = skill_md.read_text()
            title_match = re.search(r'^#\s+(.+)$', skill_content, re.MULTILINE)
            display_name = title_match.group(1) if title_match else name
        except Exception:
            display_name = name

        # Read version
        version_file = pd / "VERSION"
        version = version_file.read_text().strip() if version_file.exists() else "?"

        nodes[name] = {
            "display_name": display_name,
            "version": version,
            "brief_path": brief_path,
            "edges_out": [],
            "edges_in": [],
        }

    # Second pass: extract references
    for pd in process_dirs:
        name = pd.name
        brief_path = pd / "references" / "process-brief.md"

        if not brief_path.exists():
            continue

        brief = brief_path.read_text()

        # Find L1.9 流程外 section
        out_of_scope_match = re.search(
            r'###\s+流程外\s*\n(.*?)(?=\n---|\n##|\Z)',
            brief, re.DOTALL
        )
        if not out_of_scope_match:
            # Try English
            out_of_scope_match = re.search(
                r'###\s+Out\s+of\s+Scope\s*\n(.*?)(?=\n---|\n##|\Z)',
                brief, re.DOTALL | re.IGNORECASE
            )

        if not out_of_scope_match:
            continue

        scope_text = out_of_scope_match.group(1)

        # Extract references: lines with 指向： or target:
        ref_pattern = re.compile(
            r'[-*]\s+\*\*(.+?)\*\*\s*\n.*?指向[：:]\s*(.+?)(?:\n|$)',
            re.DOTALL
        )
        for ref_match in ref_pattern.finditer(scope_text):
            ref_desc = ref_match.group(1).strip()
            ref_target = ref_match.group(2).strip()

            # Try to resolve target to a known skill
            resolved_to = None
            # Exact match
            if ref_target in nodes:
                resolved_to = ref_target
            else:
                # Fuzzy: check if any node's display_name contains the target
                for nid, ndata in nodes.items():
                    if ref_target in ndata["display_name"] or ref_target in nid:
                        resolved_to = nid
                        break
                # Fuzzy: keyword in display name
                if not resolved_to:
                    ref_keywords = ref_target.replace("流程", "").replace("Skill", "").strip()
                    for nid, ndata in nodes.items():
                        if ref_keywords and ref_keywords in ndata["display_name"]:
                            resolved_to = nid
                            break

            edge = {
                "from": name,
                "to": resolved_to or ref_target,
                "description": ref_desc,
                "resolved": resolved_to is not None,
            }
            edges.append(edge)
            nodes[name]["edges_out"].append(resolved_to or ref_target)

            if not resolved_to:
                unresolved_refs.append(ref_target)
            else:
                nodes[resolved_to]["edges_in"].append(name)

    # Check backlinks
    for edge in edges:
        if edge["resolved"]:
            # Check if target references source back
            target_node = nodes.get(edge["to"])
            if target_node and edge["from"] not in target_node["edges_out"]:
                missing_backlinks.append(f"{edge['to']} → {edge['from']}")

    # Print results
    print(f"\n  Nodes: {len(nodes)}")
    print(f"  Edges: {len(edges)}")
    print(f"  Resolved: {sum(1 for e in edges if e['resolved'])}")
    print(f"  Unresolved: {len(unresolved_refs)}")
    print(f"  Missing backlinks: {len(missing_backlinks)}")

    if unresolved_refs:
        print(f"\n  \u26a0\ufe0f  Unresolved references:")
        for ref in unresolved_refs:
            print(f"    - {ref}")

    if missing_backlinks:
        print(f"\n  \u26a0\ufe0f  Missing backlinks:")
        for bl in missing_backlinks:
            print(f"    - {bl}")
        if args.sync:
            print(f"\n  \u2139\ufe0f  --sync mode: Backlink suggestions would be generated for each missing link.")
            print(f"    Review manually or re-run with confirmation.")

    # Mermaid graph
    print(f"\n  Mermaid Graph:")
    print(f"  ```mermaid")
    print(f"  graph LR")
    for edge in edges:
        from_name = nodes[edge["from"]]["display_name"][:12]
        to_name = edge["to"] if edge["resolved"] else edge["description"][:12]
        style = "" if edge["resolved"] else "⚠️"
        print(f"    {edge['from']}[{from_name}] -->|{style}| {edge['to']}[{to_name}]")
    print(f"  ```")

    # Orphan detection
    orphans = [nid for nid, ndata in nodes.items()
               if not ndata["edges_out"] and not ndata["edges_in"]]
    if orphans:
        print(f"\n  \u26a0\ufe0f  Orphan nodes (no connections):")
        for o in orphans:
            print(f"    - {o} ({nodes[o]['display_name']})")

    # Output to file
    if args.output:
        import json as json_module
        network_map = {
            "network_name": skills_dir.name,
            "generated_at": datetime.now().isoformat(),
            "nodes": [
                {
                    "id": nid,
                    "name": ndata["display_name"],
                    "version": ndata["version"],
                    "edges_out": len(ndata["edges_out"]),
                    "edges_in": len(ndata["edges_in"]),
                }
                for nid, ndata in nodes.items()
            ],
            "edges": edges,
            "unresolved_refs": unresolved_refs,
            "missing_backlinks": missing_backlinks,
        }
        with open(args.output, 'w') as f:
            json_module.dump(network_map, f, indent=2, ensure_ascii=False)
        print(f"\n  \u2705 Network map saved: {args.output}")


# ──────────────────────────────────────────────
# Command: meta-self-check (G10 + G11 automated enforcement)
# ──────────────────────────────────────────────

def cmd_meta_self_check(args):
    """
    Automated cross-file version consistency check.
    Enforces SELF-VALIDATION G10 (5-file version consistency) and
    G11 (examples generated_by_meta_skill_version matches current).
    Exits 1 on any mismatch.
    """
    import re as _re

    root = Path(args.root or ".").resolve()
    # Walk up if VERSION not in cwd
    while not (root / "VERSION").exists() and root.parent != root:
        root = root.parent
    if not (root / "VERSION").exists():
        print("❌ No VERSION file found ascending from cwd.")
        sys.exit(2)

    print(f"\U0001f50d Meta self-check from: {root}\n")

    target = (root / "VERSION").read_text().strip()
    sources = {"VERSION file": target}

    # CLI internal VERSION
    cli_path = root / "cli" / "meta-skill-process-architect.py"
    if cli_path.exists():
        m = _re.search(r'^VERSION\s*=\s*"([^"]+)"', cli_path.read_text(), _re.MULTILINE)
        sources["cli/...py VERSION"] = m.group(1) if m else "MISSING"
    else:
        sources["cli/...py VERSION"] = "NO FILE"

    # README badge
    readme = root / "README.md"
    if readme.exists():
        m = _re.search(r"version-([\d.]+)-blue", readme.read_text())
        sources["README badge"] = m.group(1) if m else "MISSING"
    else:
        sources["README badge"] = "NO FILE"

    # SELF-VALIDATION title
    sv = root / "SELF-VALIDATION.md"
    if sv.exists():
        first_line = sv.read_text().split("\n", 1)[0]
        m = _re.search(r"v(\d+\.\d+\.\d+)", first_line)
        sources["SELF-VALIDATION title"] = m.group(1) if m else "MISSING"
    else:
        sources["SELF-VALIDATION title"] = "NO FILE"

    # CHANGELOG latest entry
    cl = root / "CHANGELOG.md"
    if cl.exists():
        m = _re.search(r"^## \[([\d.]+)\]", cl.read_text(), _re.MULTILINE)
        sources["CHANGELOG latest"] = m.group(1) if m else "MISSING"
    else:
        sources["CHANGELOG latest"] = "NO FILE"

    print("G10 — 5-file version consistency:")
    g10_pass = True
    for name, value in sources.items():
        ok = (value == target)
        icon = "✅" if ok else "❌"
        print(f"  {icon} {name}: {value}")
        if not ok:
            g10_pass = False

    # G11: examples consistency
    print("\nG11 — examples generated_by_meta_skill_version:")
    g11_pass = True
    examples_dir = root / "examples"
    if examples_dir.exists():
        ex_skills = sorted(examples_dir.glob("*/SKILL.md"))
        if not ex_skills:
            print(f"  ⚠️  no examples/*/SKILL.md found")
        for ex in ex_skills:
            content = ex.read_text()
            m = _re.search(r"generated_by_meta_skill_version:\s*([\d.]+)", content)
            ex_ver = m.group(1) if m else "MISSING"
            ok = (ex_ver == target)
            icon = "✅" if ok else "❌"
            print(f"  {icon} {ex.parent.name}: {ex_ver}")
            if not ok:
                g11_pass = False
    else:
        print("  ⚠️  no examples/ directory")

    # G12: examples satisfy archetype-prescribed cross-cutting requirements
    # As archetype evolves, add new patterns here.
    # Each pattern: (requirement_id, requirement_name, file_glob_within_example, regex_pattern)
    archetype_requirements = [
        ("C5", "Cycle Time annotation (plan §3 C5)",
         "references/process-brief.md", r"Cycle Time:|fastest=|bottleneck="),
        ("C6", "Internal Handoff Summary (plan §3 C6)",
         "references/process-brief.md", r"Internal Handoff Summary|内部.*交接|Internal Handoff"),
    ]

    print("\nG12 — examples satisfy archetype cross-cutting requirements:")
    g12_pass = True
    if examples_dir.exists():
        ex_dirs = sorted([d for d in examples_dir.iterdir() if d.is_dir()])
        for ex_dir in ex_dirs:
            for req_id, req_name, rel_path, pattern in archetype_requirements:
                target_file = ex_dir / rel_path
                if not target_file.exists():
                    print(f"  ❌ {ex_dir.name} / {req_id}: {rel_path} not found")
                    g12_pass = False
                    continue
                content = target_file.read_text()
                if _re.search(pattern, content):
                    print(f"  ✅ {ex_dir.name} / {req_id} ({req_name.split(' (')[0]})")
                else:
                    print(f"  ❌ {ex_dir.name} / {req_id}: missing '{req_name}'")
                    g12_pass = False

    print()
    if g10_pass and g11_pass and g12_pass:
        print(f"✅ PASS — all G10/G11/G12 checks consistent at {target}")
        sys.exit(0)
    else:
        print(f"❌ FAIL — meta-skill self-consistency violated. Expected version: {target}")
        if not (g10_pass and g11_pass):
            print("\nG10/G11 fix:")
            print("  1. Bump source-of-truth (VERSION file)")
            print("  2. Sync the others: README badge, SELF-VAL title, CLI VERSION, CHANGELOG latest")
            print("  3. Update each examples/*/SKILL.md frontmatter generated_by_meta_skill_version")
        if not g12_pass:
            print("\nG12 fix:")
            print("  1. For each failing example, open references/process-brief.md")
            print("  2. Add the missing section (Cycle Time annotation or Internal Handoff Summary)")
            print("  3. Or update archetype if the requirement should no longer apply")
        print("\nThen re-run: process-architect meta-self-check")
        sys.exit(1)


# ──────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────

VERSION = "1.5.0"


def main():
    parser = argparse.ArgumentParser(
        description=f"Meta-Skill Process Architect v{VERSION} — Generate process Skills from raw materials.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s init --name "Customer Refund" --materials ./refund-docs/
  %(prog)s generate --output ./process-customer-refund/
  %(prog)s validate --skill ./process-customer-refund/
  %(prog)s package --format workbuddy --skill ./process-customer-refund/
        """,
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s v{VERSION}")

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # init
    init_parser = subparsers.add_parser("init", help="Initialize a new process analysis session")
    init_parser.add_argument("--name", required=True, help="Process name")
    init_parser.add_argument("--materials", help="Path to raw materials directory")
    init_parser.add_argument("--output", help="Output directory (default: process-{slug})")
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing output directory")

    # generate
    gen_parser = subparsers.add_parser("generate", help="Generate process Skill from materials")
    gen_parser.add_argument("--output", required=True, help="Output directory")
    gen_parser.add_argument("--force", action="store_true", help="Regenerate existing files")

    # validate
    val_parser = subparsers.add_parser("validate", help="Validate a generated process Skill")
    val_parser.add_argument("--skill", required=True, help="Path to process Skill directory")
    val_parser.add_argument("--trace", action="store_true", help="Run Trace Mode drift analysis (Phase 3)")
    val_parser.add_argument("--trace-source", help="CSV file with observed execution steps")
    val_parser.add_argument("--sla-report", help="CSV file with SLA compliance data")
    val_parser.add_argument("--source-type", choices=["jira", "linear", "asana", "manual", "csv"],
                           default="csv", help="Type of trace source data")
    val_parser.add_argument("--output", help="Output trace report to YAML file")
    val_parser.add_argument("--coverage", action="store_true", help="Run role coverage check (Phase 3)")

    # package
    pkg_parser = subparsers.add_parser("package", help="Package a process Skill for distribution")
    pkg_parser.add_argument("--skill", required=True, help="Path to process Skill directory")
    pkg_parser.add_argument("--format", default="workbuddy",
                           choices=["workbuddy", "openclaw", "claude-code", "standalone"],
                           help="Target platform format")

    # bump (Phase 3)
    bump_parser = subparsers.add_parser("bump", help="Bump version and update CHANGELOG")
    bump_parser.add_argument("--skill", required=True, help="Path to process Skill directory")
    bump_parser.add_argument("--type", required=True, choices=["major", "minor", "patch"],
                           help="Bump type (MAJOR/MINOR/PATCH)")
    bump_parser.add_argument("message", help="Changelog message describing the change")
    bump_parser.add_argument("--dry-run", action="store_true", help="Preview changes without applying")
    bump_parser.add_argument("--phase", choices=["trial", "active"], help="Set lifecycle phase on bump")
    bump_parser.add_argument("--valid-from", help="Effective date for this version (YYYY-MM-DD)")
    bump_parser.add_argument("--trial-until", help="Trial period end date (YYYY-MM-DD, only when --phase trial)")

    # which-version (Phase 5: Temporal Validity)
    wv_parser = subparsers.add_parser("which-version", help="Query which process version was active on a given date")
    wv_parser.add_argument("--skill", required=True, help="Path to process Skill directory")
    wv_parser.add_argument("--at", help="Query date (YYYY-MM-DD). If omitted, shows current version info")
    wv_parser.add_argument("--list", action="store_true", help="List all versions with temporal windows")
    wv_parser.add_argument("--phase", action="store_true", help="Show only lifecycle phase for the queried date")

    # ttl-check (Phase 3)
    ttl_parser = subparsers.add_parser("ttl-check", help="Scan Skill(s) for TTL expiry")
    ttl_parser.add_argument("--skill", help="Path to a single process Skill directory")
    ttl_parser.add_argument("--skills", help="Comma-separated paths to multiple Skill directories")
    ttl_parser.add_argument("--verbose", action="store_true", help="Show all markers including valid ones")

    # diff-plan (Phase 3)
    diff_parser = subparsers.add_parser("diff-plan", help="Compare Skill with baseline for diff-aware update")
    diff_parser.add_argument("--skill", required=True, help="Path to process Skill directory")
    diff_parser.add_argument("--since", required=True, help="Baseline version (e.g. 1.0.0) or path to baseline Skill")
    diff_parser.add_argument("--new-materials", help="Optional: path to updated materials for comparison")

    # network (Phase 3)
    net_parser = subparsers.add_parser("network", help="Build Cross-Process Network from process Skills")
    net_parser.add_argument("--skills", help="Directory containing process-* Skill directories")
    net_parser.add_argument("--skill", help="Single Skill to focus on (use with --skills-dir)")
    net_parser.add_argument("--skills-dir", help="Directory containing process-* Skills (use with --skill)")
    net_parser.add_argument("--sync", action="store_true", help="Suggest bidirectional link sync")
    net_parser.add_argument("--output", help="Output network map to JSON file")

    # impact (Phase 5)
    impact_parser = subparsers.add_parser("impact", help="Analyze impact of a process change")

    msc_parser = subparsers.add_parser("meta-self-check",
        help="Automated G10/G11 enforcement — verify cross-file version consistency + examples sync")
    msc_parser.add_argument("--root", help="Meta-skill root directory (default: walk up from cwd)")
    impact_parser.add_argument("--skill", help="Path to process Skill directory")
    impact_parser.add_argument("--skills-dir", help="Directory containing all process Skills (for cross-process impact)")
    impact_parser.add_argument("--change-type", required=True,
                              choices=["sla", "role", "tool", "step", "step-remove", "regulatory", "auto"],
                              help="Type of change being analyzed")
    impact_parser.add_argument("--step", help="Step ID affected (for sla/step changes)")
    impact_parser.add_argument("--old", help="Old value (for sla changes)")
    impact_parser.add_argument("--new", help="New value (for sla changes)")
    impact_parser.add_argument("--old-name", help="Old role name (for role changes)")
    impact_parser.add_argument("--new-name", help="New role name (for role changes)")
    impact_parser.add_argument("--old-url", help="Old URL (for tool changes)")
    impact_parser.add_argument("--new-url", help="New URL (for tool changes)")
    impact_parser.add_argument("--since", help="Baseline version for auto-detect")
    impact_parser.add_argument("--output", help="Output impact report to JSON file")

    args = parser.parse_args()

    if args.command == "init":
        cmd_init(args)
    elif args.command == "generate":
        cmd_generate(args)
    elif args.command == "validate":
        cmd_validate(args)
    elif args.command == "package":
        cmd_package(args)
    elif args.command == "bump":
        cmd_bump(args)
    elif args.command == "ttl-check":
        cmd_ttl_check(args)
    elif args.command == "diff-plan":
        cmd_diff_plan(args)
    elif args.command == "network":
        cmd_network(args)
    elif args.command == "impact":
        cmd_impact(args)
    elif args.command == "meta-self-check":
        cmd_meta_self_check(args)
    elif args.command == "which-version":
        cmd_which_version(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
